version: 0.2

phases:
  pre_build:
    commands:
      - echo Starting pre-build phase...
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo IMAGE_TAG=$IMAGE_TAG

  build:
    commands:
      - echo Building Docker image...
      - docker build -t nginx-static:$IMAGE_TAG .

  post_build:
    commands:
      - echo Docker image built successfully: nginx-static:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
